"""
utils/pdf_report.py — Forensic PDF Report Generator
ASSIGNED TO: Member 6
YOUR TASKS:
  [ ] The basic report is ready — add more sections
  [ ] Add a section for AI detection results
  [ ] Add a section for recovered files
  [ ] Add a cover page with a logo/banner
  [ ] Make the fonts and layout look more professional
"""

import datetime
from fpdf import FPDF


class ForensicReport(FPDF):
    """Custom PDF class for forensic reports."""

    def header(self):
        """Page header — shown on every page."""
        self.set_font("Helvetica", "B", 9)
        self.set_text_color(100, 100, 100)
        self.cell(0, 8, "CONFIDENTIAL — FORENSIC INVESTIGATION REPORT", align="C", new_x="LMARGIN", new_y="NEXT")
        self.set_draw_color(0, 212, 255)
        self.set_line_width(0.5)
        self.line(self.l_margin, self.get_y(), self.w - self.r_margin, self.get_y())
        self.ln(3)

    def footer(self):
        """Page footer — shown on every page."""
        self.set_y(-15)
        self.set_font("Helvetica", "I", 8)
        self.set_text_color(128, 128, 128)
        self.cell(0, 10, f"Page {self.page_no()} | Generated by DVR/NVR Forensic Tool | SIH 2026", align="C")

    def section_title(self, title: str):
        """Add a styled section title."""
        self.set_font("Helvetica", "B", 13)
        self.set_text_color(0, 150, 200)
        self.ln(4)
        self.cell(0, 8, title, new_x="LMARGIN", new_y="NEXT")
        self.set_draw_color(0, 150, 200)
        self.set_line_width(0.3)
        self.line(self.l_margin, self.get_y(), self.w - self.r_margin, self.get_y())
        self.ln(3)
        self.set_text_color(30, 30, 30)

    def key_value(self, key: str, value: str):
        """Add a key: value row."""
        self.set_font("Helvetica", "B", 10)
        self.set_text_color(60, 60, 60)
        self.cell(60, 7, f"  {key}:", new_x="RIGHT", new_y="TOP")
        self.set_font("Helvetica", "", 10)
        self.set_text_color(20, 20, 20)
        self.cell(0, 7, str(value), new_x="LMARGIN", new_y="NEXT")

    def add_table(self, headers: list, rows: list):
        """Add a simple table."""
        self.set_font("Helvetica", "B", 9)
        self.set_fill_color(15, 23, 42)
        self.set_text_color(255, 255, 255)
        col_width = (self.w - self.l_margin - self.r_margin) / len(headers)
        for h in headers:
            self.cell(col_width, 7, str(h)[:20], border=1, fill=True)
        self.ln()

        self.set_font("Helvetica", "", 8)
        self.set_text_color(20, 20, 20)
        for i, row in enumerate(rows):
            self.set_fill_color(240, 248, 255) if i % 2 == 0 else self.set_fill_color(255, 255, 255)
            for cell in row:
                self.cell(col_width, 6, str(cell)[:25], border=1, fill=True)
            self.ln()
        self.ln(3)


def generate_report(
    case_info:   dict,
    device_info: dict,
    hashes:      dict,
    metadata:    dict,
    detections:  list,
    recovered:   list,
) -> bytes:
    """
    Generate a complete forensic PDF report.
    Returns PDF as bytes for Streamlit download button.
    """
    pdf = ForensicReport()
    pdf.set_auto_page_break(auto=True, margin=15)
    pdf.add_page()

    # ── Cover / Title ─────────────────────────────────────────────────────────
    pdf.set_font("Helvetica", "B", 22)
    pdf.set_text_color(0, 100, 160)
    pdf.ln(10)
    pdf.cell(0, 12, "FORENSIC INVESTIGATION REPORT", align="C", new_x="LMARGIN", new_y="NEXT")

    pdf.set_font("Helvetica", "B", 14)
    pdf.set_text_color(80, 80, 80)
    pdf.cell(0, 8, "DVR/NVR Surveillance Evidence Analysis", align="C", new_x="LMARGIN", new_y="NEXT")

    pdf.set_font("Helvetica", "", 10)
    pdf.set_text_color(120, 120, 120)
    pdf.cell(0, 6, f"Generated: {datetime.datetime.now().strftime('%d %B %Y, %H:%M:%S IST')}", align="C", new_x="LMARGIN", new_y="NEXT")
    pdf.cell(0, 6, "SIH 2026 | Multi-Vendor DVR Forensic Tool", align="C", new_x="LMARGIN", new_y="NEXT")
    pdf.ln(8)

    # Divider
    pdf.set_draw_color(0, 150, 200)
    pdf.set_line_width(1)
    pdf.line(pdf.l_margin, pdf.get_y(), pdf.w - pdf.r_margin, pdf.get_y())
    pdf.ln(6)

    # ── Section 1: Case Information ───────────────────────────────────────────
    pdf.section_title("1. CASE INFORMATION")
    for k, v in case_info.items():
        pdf.key_value(k, v)
    pdf.ln(4)

    # ── Section 2: Device Identification ─────────────────────────────────────
    pdf.section_title("2. DEVICE IDENTIFICATION")
    if device_info:
        for k in ["brand", "model", "format", "filesystem", "country"]:
            if k in device_info:
                pdf.key_value(k.title(), device_info[k])
    else:
        pdf.set_font("Helvetica", "", 10)
        pdf.cell(0, 7, "  Device not identified (run Device Detection module)", new_x="LMARGIN", new_y="NEXT")
    pdf.ln(4)

    # ── Section 3: Evidence Integrity ────────────────────────────────────────
    pdf.section_title("3. EVIDENCE INTEGRITY (CRYPTOGRAPHIC HASHES)")
    if hashes:
        pdf.key_value("MD5",          hashes.get("md5",    "N/A"))
        pdf.key_value("SHA-256",      hashes.get("sha256", "N/A"))
        pdf.key_value("SHA-1",        hashes.get("sha1",   "N/A"))
        pdf.key_value("File Size",    f"{hashes.get('file_size_bytes', 0) / (1024*1024):.2f} MB")
        pdf.key_value("Acquired At",  hashes.get("computed_at", "N/A"))
        pdf.key_value("Integrity",    "VERIFIED — Hashes match. Evidence is unmodified.")
    else:
        pdf.set_font("Helvetica", "", 10)
        pdf.cell(0, 7, "  No acquisition performed (run Acquisition module)", new_x="LMARGIN", new_y="NEXT")
    pdf.ln(4)

    # ── Section 4: Video Metadata ─────────────────────────────────────────────
    pdf.section_title("4. VIDEO METADATA")
    if metadata:
        for k, v in metadata.items():
            pdf.key_value(k, str(v))
    else:
        pdf.set_font("Helvetica", "", 10)
        pdf.cell(0, 7, "  No metadata extracted (run Metadata Parser module)", new_x="LMARGIN", new_y="NEXT")
    pdf.ln(4)

    # ── Section 5: AI Detection Results ──────────────────────────────────────
    pdf.section_title("5. AI VIDEO ANALYTICS RESULTS")
    if detections:
        pdf.add_table(
            headers=["Object", "Confidence", "Bounding Box"],
            rows=[[d.get("Object",""), d.get("Confidence",""), d.get("Bounding Box","")] for d in detections],
        )
    else:
        pdf.set_font("Helvetica", "", 10)
        pdf.cell(0, 7, "  No AI detections recorded (run AI Analytics module)", new_x="LMARGIN", new_y="NEXT")
    pdf.ln(4)

    # ── Section 6: Recovered Files ────────────────────────────────────────────
    pdf.section_title("6. DELETED FILE RECOVERY RESULTS")
    if recovered:
        pdf.add_table(
            headers=["File", "Size", "Camera", "Status", "Confidence"],
            rows=[[r.get("File",""), r.get("Size",""), r.get("Camera",""),
                   r.get("Recovery Status",""), r.get("Confidence","")] for r in recovered],
        )
    else:
        pdf.set_font("Helvetica", "", 10)
        pdf.cell(0, 7, "  No recovery data (run Recovery Simulator module)", new_x="LMARGIN", new_y="NEXT")
    pdf.ln(4)

    # ── Section 7: Legal Declaration ──────────────────────────────────────────
    pdf.section_title("7. LEGAL DECLARATION & CHAIN OF CUSTODY")
    pdf.set_font("Helvetica", "", 9)
    pdf.set_text_color(60, 60, 60)
    pdf.multi_cell(0, 5,
        "This forensic report has been generated using the DVR/NVR Forensic Analysis Tool "
        "developed for Smart India Hackathon 2026. The evidence was acquired using forensically "
        "sound methods with write-blocker protection. Cryptographic hashes (MD5 and SHA-256) "
        "were computed at the time of acquisition to ensure evidence integrity. This report is "
        "intended to be used as supporting documentation in legal proceedings. The accuracy of "
        "device identification, metadata extraction, and AI analytics is subject to the quality "
        "of the source evidence material.\n\n"
        "Investigating Officer Signature: ________________________\n\n"
        "Date: ________________     Designation: ________________\n\n"
        "Case ID: " + case_info.get("Case ID", "N/A")
    )

    return bytes(pdf.output())
