"""
utils/pdf_report.py — Forensic PDF Report Generator
ASSIGNED TO: Member 6
YOUR TASKS:
  [ ] The basic report is ready — add more sections
  [ ] Add a section for AI detection results
  [ ] Add a section for recovered files
  [ ] Add a cover page with a logo/banner
  [ ] Make the fonts and layout look more professional
"""

"""
utils/pdf_report.py
Forensic PDF Report Generator — Member 6
"""

from datetime import datetime
from typing import Any

from fpdf import FPDF


def clean_text(value: Any, limit: int | None = None) -> str:
    """Convert values into PDF-safe text for Helvetica's built-in font."""
    if value is None:
        text = "Not available"
    elif isinstance(value, dict):
        text = "; ".join(f"{k}: {v}" for k, v in value.items())
    elif isinstance(value, (list, tuple, set)):
        text = ", ".join(str(item) for item in value)
    else:
        text = str(value)

    replacements = {
        "—": "-",
        "–": "-",
        "•": "-",
        "✅": "[OK]",
        "⚠️": "[Pending]",
        "✓": "[OK]",
        "✗": "[X]",
        "…": "...",
        "₹": "Rs.",
    }

    for old, new in replacements.items():
        text = text.replace(old, new)

    # Helvetica supports latin-1 only.
    text = text.encode("latin-1", "replace").decode("latin-1")

    if limit and len(text) > limit:
        return text[: limit - 3] + "..."
    return text


def value_from(data: dict, *possible_keys: str, default: str = "N/A") -> Any:
    """Read a dictionary value without depending on exact key capitalisation."""
    normalised = {
        str(key).lower().replace("_", " ").strip(): value
        for key, value in (data or {}).items()
    }

    for key in possible_keys:
        matched = normalised.get(key.lower().replace("_", " ").strip())
        if matched not in (None, ""):
            return matched

    return default


class ForensicReport(FPDF):
    """Professional, court-report-style PDF layout."""

    NAVY = (15, 35, 58)
    BLUE = (0, 126, 167)
    PALE_BLUE = (231, 244, 250)
    LIGHT_GREY = (245, 247, 250)
    DARK_GREY = (65, 72, 81)
    RED = (176, 45, 45)
    GREEN = (32, 125, 84)

    def __init__(self):
        super().__init__()
        self.set_margins(15, 16, 15)
        self.set_auto_page_break(auto=True, margin=18)
        self.case_id = "N/A"

    def header(self):
        """Header is hidden on the cover page and shown on report pages."""
        if self.page_no() == 1:
            return

        self.set_fill_color(*self.NAVY)
        self.rect(0, 0, self.w, 15, "F")

        self.set_y(4)
        self.set_font("Helvetica", "B", 8)
        self.set_text_color(255, 255, 255)
        self.cell(0, 5, "DVR / NVR FORENSIC EXAMINATION REPORT", align="L")

        self.set_font("Helvetica", "", 8)
        self.cell(0, 5, f"Case ID: {clean_text(self.case_id, 35)}", align="R")

        self.set_y(20)
        self.set_text_color(0, 0, 0)

    def footer(self):
        """Footer on every page."""
        self.set_y(-13)
        self.set_draw_color(190, 195, 200)
        self.line(self.l_margin, self.get_y(), self.w - self.r_margin, self.get_y())

        self.set_y(-10)
        self.set_font("Helvetica", "I", 7.5)
        self.set_text_color(110, 110, 110)
        self.cell(
            0,
            5,
            f"Generated by DVR/NVR Forensic Tool | Page {self.page_no()}",
            align="C",
        )
        self.set_text_color(0, 0, 0)

    def cover_page(self, case_info: dict):
        """Create a clean report cover page."""
        self.add_page()

        # Banner
        self.set_fill_color(*self.NAVY)
        self.rect(0, 0, self.w, 60, "F")

        self.set_y(18)
        self.set_font("Helvetica", "B", 24)
        self.set_text_color(255, 255, 255)
        self.cell(0, 12, "FORENSIC", align="C", new_x="LMARGIN", new_y="NEXT")
        self.cell(0, 12, "INVESTIGATION REPORT", align="C", new_x="LMARGIN", new_y="NEXT")

        self.set_font("Helvetica", "", 11)
        self.set_text_color(210, 230, 240)
        self.cell(
            0,
            8,
            "DVR / NVR Surveillance Evidence Analysis",
            align="C",
            new_x="LMARGIN",
            new_y="NEXT",
        )

        self.set_y(82)
        self.set_text_color(0, 0, 0)
        self.set_font("Helvetica", "B", 14)
        self.cell(0, 8, "CASE DOSSIER", align="C", new_x="LMARGIN", new_y="NEXT")

        self.ln(12)
        self.cover_field("Case / FIR Number", value_from(case_info, "Case ID", "Case / FIR Number"))
        self.cover_field("Investigating Officer", value_from(case_info, "Investigating Officer", "Officer"))
        self.cover_field("Department / Unit", value_from(case_info, "Department"))
        self.cover_field("Incident Location", value_from(case_info, "Incident Location", "Crime Location"))
        self.cover_field("Classification", value_from(case_info, "Classification", default="RESTRICTED"))
        self.cover_field("Report Date", value_from(case_info, "Report Date"))

        self.set_y(-43)
        self.set_fill_color(*self.PALE_BLUE)
        self.rect(self.l_margin, self.get_y(), self.w - self.l_margin - self.r_margin, 24, "F")
        self.set_xy(self.l_margin + 5, self.get_y() + 5)
        self.set_font("Helvetica", "I", 8.5)
        self.set_text_color(*self.DARK_GREY)
        self.multi_cell(
            self.w - self.l_margin - self.r_margin - 10,
            4,
            "This document is an automated forensic-analysis summary. "
            "Findings should be independently reviewed and handled according to "
            "applicable evidence, chain-of-custody and legal procedures.",
        )
        self.set_text_color(0, 0, 0)

    def cover_field(self, label: str, value: Any):
        self.set_font("Helvetica", "B", 9)
        self.set_text_color(*self.BLUE)
        self.cell(55, 8, label.upper())

        self.set_font("Helvetica", "", 10)
        self.set_text_color(0, 0, 0)
        self.multi_cell(0, 8, clean_text(value))

        self.set_draw_color(220, 225, 230)
        self.line(self.l_margin, self.get_y(), self.w - self.r_margin, self.get_y())
        self.ln(2)

    def section_title(self, number: str, title: str):
        self.ln(5)
        self.set_fill_color(*self.NAVY)
        self.set_text_color(255, 255, 255)
        self.set_font("Helvetica", "B", 11)
        self.cell(10, 8, number, align="C", fill=True)

        self.set_fill_color(*self.PALE_BLUE)
        self.set_text_color(*self.NAVY)
        self.cell(
            self.w - self.l_margin - self.r_margin - 10,
            8,
            f"  {title.upper()}",
            fill=True,
            new_x="LMARGIN",
            new_y="NEXT",
        )
        self.set_text_color(0, 0, 0)
        self.ln(2)

    def note(self, text: str, warning: bool = False):
        if warning:
            self.set_fill_color(255, 243, 230)
            self.set_text_color(*self.RED)
        else:
            self.set_fill_color(*self.PALE_BLUE)
            self.set_text_color(*self.DARK_GREY)

        self.set_font("Helvetica", "I", 8.5)
        self.multi_cell(
            0,
            5,
            clean_text(text),
            fill=True,
            new_x="LMARGIN",
            new_y="NEXT",
        )
        self.set_text_color(0, 0, 0)
        self.ln(2)

    def key_value_table(self, data: dict):
        """Add a two-column details table."""
        if not data:
            self.note("No data was available from this analysis module.", warning=True)
            return

        key_width = 57
        value_width = self.w - self.l_margin - self.r_margin - key_width

        for index, (key, value) in enumerate(data.items()):
            fill = index % 2 == 0
            self.set_fill_color(*self.LIGHT_GREY)

            self.set_font("Helvetica", "B", 8.5)
            self.set_text_color(*self.DARK_GREY)
            self.cell(
                key_width,
                7,
                clean_text(str(key).replace("_", " ").title(), 35),
                border=1,
                fill=fill,
            )

            self.set_font("Helvetica", "", 8.5)
            self.set_text_color(0, 0, 0)
            self.cell(
                value_width,
                7,
                clean_text(value, 90),
                border=1,
                fill=fill,
                new_x="LMARGIN",
                new_y="NEXT",
            )

        self.ln(2)

    def table(self, headers: list[str], rows: list[list[Any]], widths: list[float]):
        """Add a compact, professional table."""
        if not rows:
            self.note("No records were returned by this analysis module.", warning=True)
            return

        self.set_font("Helvetica", "B", 8)
        self.set_fill_color(*self.NAVY)
        self.set_text_color(255, 255, 255)

        for header, width in zip(headers, widths):
            self.cell(width, 7, clean_text(header, 22), border=1, fill=True)
        self.ln()

        self.set_text_color(0, 0, 0)
        for row_index, row in enumerate(rows):
            self.set_font("Helvetica", "", 7.5)
            self.set_fill_color(*self.LIGHT_GREY)
            fill = row_index % 2 == 0

            for value, width in zip(row, widths):
                self.cell(
                    width,
                    6,
                    clean_text(value, 30),
                    border=1,
                    fill=fill,
                )
            self.ln()

        self.ln(2)


def normalise_records(records: Any) -> list[dict]:
    """Ensure output from different teammate modules is usable."""
    if not records:
        return []

    if isinstance(records, dict):
        return [records]

    if isinstance(records, list):
        return [
            item if isinstance(item, dict) else {"Result": item}
            for item in records
        ]

    return [{"Result": records}]


def generate_report(
    case_info: dict,
    device_info: dict,
    hashes: dict,
    metadata: dict,
    detections: list,
    recovered: list,
) -> bytes:
    """Generate a complete forensic PDF report and return it as bytes."""

    pdf = ForensicReport()
    pdf.case_id = clean_text(value_from(case_info, "Case ID", "Case / FIR Number"))
    pdf.cover_page(case_info)

    # Page 2 begins the actual report.
    pdf.add_page()

    # 1. Executive evidence summary
    pdf.section_title("1", "Executive Evidence Summary")

    completed_modules = sum(
        bool(item)
        for item in [device_info, hashes, metadata, detections, recovered]
    )

    summary = {
        "Case Identifier": value_from(case_info, "Case ID", "Case / FIR Number"),
        "Evidence Description": value_from(case_info, "Evidence Description"),
        "Case Priority": value_from(case_info, "Priority"),
        "Analysis Modules Available": f"{completed_modules} of 5",
        "Report Generated": datetime.now().strftime("%d %B %Y, %H:%M:%S"),
    }
    pdf.key_value_table(summary)

    if completed_modules == 5:
        pdf.note("All analysis modules supplied findings for this report.")
    else:
        pdf.note(
            f"{5 - completed_modules} analysis module(s) did not supply findings. "
            "Their report sections are retained as documented placeholders.",
            warning=True,
        )

    # 2. Case information
    pdf.section_title("2", "Case Information")
    pdf.key_value_table(case_info)

    # 3. Device
    pdf.section_title("3", "Device Identification")
    if device_info:
        device_fields = {
            "Brand": value_from(device_info, "brand", "manufacturer"),
            "Model": value_from(device_info, "model", "device model"),
            "File Format": value_from(device_info, "format", "file format"),
            "File System": value_from(device_info, "filesystem", "file system"),
            "Country / Region": value_from(device_info, "country", "region"),
        }
        # Also include non-standard fields that another member may add.
        for key, value in device_info.items():
            if key not in device_fields:
                device_fields[key] = value
        pdf.key_value_table(device_fields)
    else:
        pdf.note("Device Detection module has not provided any findings.", warning=True)

    # 4. Hashes
    pdf.section_title("4", "Evidence Integrity & Hash Values")
    if hashes:
        file_size = value_from(hashes, "file_size_bytes", "file size bytes", default=0)
        try:
            file_size_text = f"{float(file_size) / (1024 * 1024):.2f} MB"
        except (TypeError, ValueError):
            file_size_text = clean_text(file_size)

        integrity = "Hash values recorded - verify against the original acquisition record."
        hash_fields = {
            "MD5": value_from(hashes, "md5"),
            "SHA-256": value_from(hashes, "sha256", "sha-256"),
            "SHA-1": value_from(hashes, "sha1", "sha-1"),
            "Evidence File Size": file_size_text,
            "Computed / Acquired At": value_from(hashes, "computed_at", "acquired at"),
            "Integrity Status": integrity,
        }
        pdf.key_value_table(hash_fields)
        pdf.note(
            "Cryptographic hashes support integrity verification. "
            "A matching hash comparison should be documented separately where required."
        )
    else:
        pdf.note("Acquisition and hash-generation data is not available.", warning=True)

    # 5. Metadata
    pdf.section_title("5", "Video Metadata & Timeline")
    if metadata:
        pdf.key_value_table(metadata)
    else:
        pdf.note("Metadata Parser module has not provided video properties or timeline data.", warning=True)

    # 6. AI findings
    pdf.section_title("6", "AI Video Analytics Findings")
    detection_records = normalise_records(detections)

    if detection_records:
        detection_rows = []
        for item in detection_records:
            detection_rows.append(
                [
                    value_from(item, "object", "class", "label", "detected object", default="-"),
                    value_from(item, "confidence", "score", default="-"),
                    value_from(item, "timestamp", "time", "frame time", default="-"),
                    value_from(item, "bounding box", "bbox", "location", default="-"),
                ]
            )

        available_labels = {
            clean_text(value_from(item, "object", "class", "label", default="Unknown"))
            for item in detection_records
        }

        pdf.key_value_table(
            {
                "Total Detection Events": len(detection_records),
                "Detected Categories": ", ".join(sorted(available_labels)),
            }
        )
        pdf.table(
            headers=["Object / Class", "Confidence", "Timestamp", "Location"],
            rows=detection_rows,
            widths=[43, 32, 36, 64],
        )
        pdf.note(
            "AI findings are automated indicators and should be reviewed by the investigating officer "
            "against the original footage."
        )
    else:
        pdf.note("AI Analytics module has not recorded any detection results.", warning=True)

    # 7. Recovery
    pdf.section_title("7", "Deleted Footage Recovery Findings")
    recovery_records = normalise_records(recovered)

    if recovery_records:
        recovery_rows = []
        for item in recovery_records:
            recovery_rows.append(
                [
                    value_from(item, "file", "filename", "name", default="-"),
                    value_from(item, "size", "file size", default="-"),
                    value_from(item, "camera", "channel", default="-"),
                    value_from(item, "recovery status", "status", default="-"),
                    value_from(item, "confidence", "recovery confidence", default="-"),
                ]
            )

        pdf.key_value_table(
            {
                "Total Recovery Entries": len(recovery_records),
                "Recovery Note": (
                    "Simulator results indicate potential recoverable entries; "
                    "validate results using approved forensic recovery procedures."
                ),
            }
        )
        pdf.table(
            headers=["File", "Size", "Camera", "Status", "Confidence"],
            rows=recovery_rows,
            widths=[53, 27, 30, 38, 27],
        )
    else:
        pdf.note("Recovery Simulator module has not provided any recovery results.", warning=True)

    # 8. Declaration
    pdf.section_title("8", "Examiner Declaration & Chain of Custody")
    pdf.set_font("Helvetica", "", 9)
    pdf.set_text_color(*pdf.DARK_GREY)

    declaration = (
        "This report records findings generated from the supplied evidence and analysis modules "
        "within the DVR/NVR Forensic Tool. The examiner is responsible for verifying the findings, "
        "preserving original evidence, documenting chain of custody, and complying with all "
        "applicable organisational and legal requirements before relying on this report."
    )
    pdf.multi_cell(0, 5.5, declaration)

    pdf.ln(12)
    pdf.set_font("Helvetica", "B", 9)
    pdf.set_text_color(0, 0, 0)
    pdf.cell(88, 7, "Investigating Officer Signature: ____________________")
    pdf.cell(0, 7, "Date: ____________________")
    pdf.ln(12)
    pdf.cell(88, 7, "Examiner Name / Designation: _____________________")
    pdf.cell(0, 7, "Seal / Reference: ______________")

    return bytes(pdf.output())